name: cisco
label: Cisco CPE GPCS Config
description: CPE config for Cisco
type: template
extends:

labels:
  service_type: gpcs-cpe


variables:
- name: service_ip
  description: Service IP Address
  default: 192.0.9.1
  type_hint: text
- name: preshared_key
  description: Preshared Key
  default: 12345678
  type_hint: text
- name: tunnel_source
  description: Tunnel Source Interface
  default: GigabitEthernet1
  type_hint: text
- name: match_address
  description: Subnet mapped to tunnel interface
  default: 192.0.10.1
  type_hint: text
- name: match_netmask
  description: Netmask for match subnet
  default: 255.255.255.0
  type_hint: text
- name: tunnel_ip
  description: Destination IP of the tunnel
  default: 192.0.11.1
  type_hint: text
- name: tunnel_netmask
  description: Network mask for tunnel interface
  default: 255.255.255.255
  type_hint: text


snippets:
- name: cisco_ipsec.conf
  file: cisco_ipsec.conf


