# bronze security templates for basic level security without threat, URL, or WF subscriptions
# requires ignoring the Palo Alto Networks published EDL rules from IronSkillet
# xml snippets not in the local directory pull from the gold master set of snippets

name: bronze_panos_v90
label: Bronze
description: Bronze Basic Security panos
type: panos
extends: internet_gateway_base_panos_v90

labels:
  service_type: internet_gateway_panos
  collection: mssp

variables:
  - name: FW_NAME
    description: Device Name
    default: panos-01
    type_hint: text
  - name: INTF_TRUST
    description: Trust Interface
    default: ethernet1/1
    type_hint: text
  - name: INTF_UNTRUST
    description: Untrust Interface
    default: ethernet1/2
    type_hint: text
  - name: IP_12
    description: IP 12
    default: 192.168.1.1/24
    type_hint: ip_address
  - name: ZONE_TRUST
    description: trust zone
    default: trust
    type_hint: text
  - name: ZONE_UNTRUST
    description: untrust zone name
    default: untrust
    type_hint: text
# toggle to NOT load the EDL security rules found in IronSkillet
# not best practice but these EDLs require a threat protect subscription
  - name: INCLUDE_PAN_EDL
    description: include the predefined Palo Alto Networks external lists
    default: False
    type_hint: dropdown
    dd_list:
      - key: yes
        value: True
      - key: no
        value: False

snippets:
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
    file: tag.xml
  - name: security_rules-security-rules-bronze
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security
    file: security_rules_bronze.xml

