name: internet_gateway_base_panos
label: Internet Gateway Base Snippets
description: Internet Gateway Base
type: panos
extends: snippets_panos

labels:
  service_type: internet_gateway_base_panos
  collection: mssp

variables:
  - name: FW_NAME
    description: Device Name
    default: panos-01
    type_hint: text
  - name: INTF_TRUST
    description: Trust Interface
    default: ethernet1/1
    type_hint: text
  - name: INTF_UNTRUST
    description: Untrust Interface
    default: ethernet1/2
    type_hint: text
  - name: IP_12
    description: IP 12
    default: 192.168.1.1/24
    type_hint: ip_address
  - name: ZONE_TRUST
    description: trust zone
    default: trust
    type_hint: text
  - name: ZONE_UNTRUST
    description: untrust zone name
    default: untrust
    type_hint: text

snippets:
  - name: network_profiles-network-profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/profiles
    file: network_profiles.xml
  - name: interface
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface
    file: interface.xml
  - name: virtual_router
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    file: virtual_router.xml
  - name: vsys_imports
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/import
    file: vsys_imports.xml
  - name: zone
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
    file: zone.xml
  - name: nat-source-nat-to-untrust
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/nat
    file: source_nat_to_untrust.xml


